### PR TITLE
Update Tutorial for Summer School 2024

### PR DESCRIPTION
**Pull request by marcus-voss**
Adding forecasting book as reference for further reading. 
Adding references on transformers. 
Adding references to new CCAI tutorials. 
Adding blank cells

### CODE REVIEW

**Comment by mdhanna** [comment]
The updates look great, thank you!

My only request is to run all the cells (as well as the solutions to the exercises) so that the expected output is visible.

**Review by mdhanna — CHANGES_REQUESTED** [review]
The updates look excellent, thank you!

My only request is to run all the cells (as well as the solutions to the exercises) so that the expected output is visible.

**Comment by marcus-voss** [comment]
Have now included the cell output (sorry, habit, as at work we are supposed to delete the output before committing notebooks ;))

**Review by mdhanna — APPROVED** [review]
Thanks Marcus! The notebook looks great, and you are ready to start recording the video walkthrough when you're able.

**Pull request merged**
